# Generated by Django 5.1.7 on 2025-04-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='order',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orders/'),
        ),
    ]
