# Generated by Django 5.1.7 on 2025-04-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_remove_product_uploaded_file_order_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/orders/'),
        ),
    ]
