# Generated by Django 5.1.7 on 2025-04-15 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaSessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('session_type', models.CharField(blank=True, choices=[('contract', 'Contract'), ('solo', 'Solo')], max_length=10, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('massage', 'Relaxing Massage'), ('facial', 'Rejuvenating Facial'), ('aromatic', 'Aromatic Oil Therapy'), ('bath', 'Lavender Bath Soak')], max_length=20, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spa_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
