# Generated by Django 5.1.7 on 2025-04-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_spasessionbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spasessionbooking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='spasessionbooking',
            name='full_name',
        ),
    ]
